apiVersion: v1
kind: ConfigMap
metadata:
  name: logcontrol-configmap
data:
  # file-like keys
  logcontrol.json: |
    [
      {
        "container": "my-container-from-container",
        "severity": "info"
      }
    ]
