apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: app
          image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
            - name: LOG_CTRL_FILE
              value: "/logcontrol/logcontrol.json"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /logcontrol
              name: foo
      volumes:
        - name: foo
          configMap:
            name: logcontrol-configmap